CREATE TABLE EMPLOYEE(
NAME TEXT,
AGE INTEGER,
SALARY INTEGER,
DEPARTMENT TEXT,
ADDRESS TEXT);
INSERT INTO EMPLOYEE (NAME,AGE,SALARY,DEPARTMENT)VALUES
('JOSEPH',25,50000,'IT','NEW YORK')
('ALINE',20,60000,'ACCOUNTING','LOS ANGELES'),
('JOHN',35,45000,'HR','CHICAGO'),
('MARRIE',28,70000,'IT','SAN FRANSISCO'),
('JAMES',30,55000,'ACCOUNTING','BOSTON'),
('SARAH',22,48000,'HR','MIAMI');
SELECT *FROM EMPLOYEE ;
SELECT *FROM EMPLOYEE  WHERE AGE=20 AND ADDRESS='LOS ANGELES';
SELECT *FROM EMPLOYEE  WHERE AGE=28
SELECT *FROM EMPLOYEE  WHERE NAME='SARAH' OR NAME='MARRIE';
SELECT *FROM EMPLOYEE  WHERE NAME='JOHN' OR AGE =30;
SELECT *FROM EMPLOYEE  WHERE DEPARTMENT='ACCOUNTING' AND (ADDRESS='BOSTON' OR ADDRESS='LOS ANGELES');
SELECT *FROM EMPLOYEE WHERE DEPARTMENT='IT' AND (NAME='MARRIE'OR NAME='JOSEPH');