CREATE TABLE STUDENT(
NUMBER TEXT PRIMARY KEY,
NAME TEXT ,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER);
INSERT INTO STUDENT(NUMBER,NAME,ADDRESS,PHONE,AGE)VALUES
('1','RAM','DELHI','******','18'),
('2','RAMESH','BIERUT','******','18'),
('3','JAD','ALEY','******','21'),
('4','HADDAD','BEIRUT','******','20'),
('5','JOSEPH','ALEY','******','19'),
('6','JAD','NEW YORK','******','21');
SELECT *FROM STUDENT ;
SELECT *FROM STUDENT WHERE AGE=18 AND ADDRESS='DELHI';
SELECT *FROM STUDENT WHERE AGE=18 NAME='RAM';
SELECT *FROM STUDENT WHERE NAME='JAD' OR NAME='JOSEPH';
SELECT *FROM STUDENT WHERE NAME='HADDAD' OR AGE =20;
SELECT *FROM STUDENT WHERE NAME='JAD' AND (ADDRESS='ALEY' OR ADDRESS='NEW YORK');
SELECT *FROM STUDENT WHERE AGE='21' AND (ADDRESS='ALEY' OR ADDRESS='NEW YORK');